general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.inactive_border = $on_primary
    col.active_border = $primary $surface_container $primary $surface_container $primary $surface_container $primary $surface_container $primary $surface_container
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

#scrolling {
#    column_width = 0.5,1.0          # fraction of screen width per column (0.5–1.0 common; default might be ~0.7 or so)
#    fullscreen_on_one_column = true  # if only one column, make it fullscreen-ish
#    direction = right           # new windows appear to the right (or left/down/up)
#}
