hl.bind(mainMod .. " + " .. turnMod, hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("wf-recorder -f ~/Videos/blxshell-V3-$(date +%Y%m%d-%H%M%S).mp4"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("killall wf-recorder"))
hl.bind(mainMod .. " + SPACE", hl.dsp.global("quickshell:LauncherToggle"))
hl.bind(mainMod .. " + C", hl.dsp.global("quickshell:untoggleKB"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd([[randwall && notify-send -i "$HOME/Downloads/casino_33dp_E3E3E3_FILL0_wght400_GRAD0_opsz40.svg" "Hi Unixporn!" "Check out my dotfiles!"]]))
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + I", hl.dsp.global("quickshell:toggleKB"))
hl.bind("PRINT", hl.dsp.exec_cmd("wlshot screen wlrclipboard=1"))
hl.bind("ALT + Space", hl.dsp.global("quickshell:togglePie"))
hl.bind(mainMod .. " + code:45", hl.dsp.global("quickshell:toggleKB"))
hl.bind(mainMod .. " + code:9", hl.dsp.global("quickshell:untoggleKB"))
hl.bind(mainMod .. " + S", hl.dsp.global("quickshell:SettingsToggle"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("blxshell lock"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("blxshell powermenu"))
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true, locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { repeating = true, locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
