$image = YOUR_WALLPAPER_PATH

$background = rgba(121413ff)

$on_background = rgba(626261ff)

$surface = rgba(121413ff)

$surface_dim = rgba(121413ff)

$surface_bright = rgba(383939ff)

$surface_container_lowest = rgba(0d0e0eff)

$surface_container_low = rgba(1b1c1bff)

$surface_container = rgba(1f201fff)

$surface_container_high = rgba(292a29ff)

$surface_container_highest = rgba(343534ff)

$on_surface = rgba(cbcbc9ff)

$on_surface_variant = rgba(9ea4a1ff)

$inverse_surface = rgba(e3e2e1ff)

$inverse_on_surface = rgba(474847ff)

$outline = rgba(7e8582ff)

$outline_variant = rgba(353b39ff)

$shadow = rgba(000000ff)

$scrim = rgba(000000ff)

$primary = rgba(8fa8a0ff)

$on_primary = rgba(041b16ff)

$primary_container = rgba(283e38ff)

$on_primary_container = rgba(90a9a1ff)

$inverse_primary = rgba(516962ff)

$secondary = rgba(9ba5a1ff)

$on_secondary = rgba(111917ff)

$secondary_container = rgba(333c39ff)

$on_secondary_container = rgba(9ca6a2ff)

$tertiary = rgba(a3a0b7ff)

$on_tertiary = rgba(161627ff)

$tertiary_container = rgba(39384bff)

$on_tertiary_container = rgba(a4a1b8ff)

$error = rgba(ff7b6eff)

$on_error = rgba(390001ff)

$error_container = rgba(7b0007ff)

$on_error_container = rgba(ff7d70ff)

$primary_fixed = rgba(112923ff)

$primary_fixed_dim = rgba(283e38ff)

$on_primary_fixed = rgba(b8d2c9ff)

$on_primary_fixed_variant = rgba(90a9a1ff)

$secondary_fixed = rgba(1e2624ff)

$secondary_fixed_dim = rgba(333c39ff)

$on_secondary_fixed = rgba(c5cecaff)

$on_secondary_fixed_variant = rgba(9ca6a2ff)

$tertiary_fixed = rgba(242334ff)

$tertiary_fixed_dim = rgba(39384bff)

$on_tertiary_fixed = rgba(cdc9e1ff)

$on_tertiary_fixed_variant = rgba(a4a1b8ff)

$foreground = rgba(626261ff)

$surface_variant = rgba(343534ff)
