-- Generated by blxshell col_gen. Do not edit manually.
local colors = {
    image = [[YOUR_WALLPAPER_PATH]],

    background = "rgba(1e100cff)",

    on_background = "rgba(735d57ff)",

    surface = "rgba(1e100cff)",

    surface_dim = "rgba(1e100cff)",

    surface_bright = "rgba(473530ff)",

    surface_container_lowest = "rgba(180b07ff)",

    surface_container_low = "rgba(271813ff)",

    surface_container = "rgba(2c1c17ff)",

    surface_container_high = "rgba(372621ff)",

    surface_container_highest = "rgba(43312bff)",

    on_surface = "rgba(e1c5bdff)",

    on_surface_variant = "rgba(be9b91ff)",

    inverse_surface = "rgba(fadcd4ff)",

    inverse_on_surface = "rgba(57433eff)",

    outline = "rgba(9c7c73ff)",

    outline_variant = "rgba(4d342dff)",

    shadow = "rgba(000000ff)",

    scrim = "rgba(000000ff)",

    primary = "rgba(ff7d56ff)",

    on_primary = "rgba(340700ff)",

    primary_container = "rgba(701b00ff)",

    on_primary_container = "rgba(ff7f59ff)",

    inverse_primary = "rgba(ba3300ff)",

    secondary = "rgba(f48362ff)",

    on_secondary = "rgba(340700ff)",

    secondary_container = "rgba(6d1e05ff)",

    on_secondary_container = "rgba(f68463ff)",

    tertiary = "rgba(c0a037ff)",

    on_tertiary = "rgba(1f1700ff)",

    tertiary_container = "rgba(483800ff)",

    on_tertiary_container = "rgba(c1a138ff)",

    error = "rgba(ff7b6eff)",

    on_error = "rgba(390001ff)",

    error_container = "rgba(7b0007ff)",

    on_error_container = "rgba(ff7d70ff)",

    primary_fixed = "rgba(4a0f00ff)",

    primary_fixed_dim = "rgba(701b00ff)",

    on_primary_fixed = "rgba(ffbcaaff)",

    on_primary_fixed_variant = "rgba(ff7f59ff)",

    secondary_fixed = "rgba(4a0f00ff)",

    secondary_fixed_dim = "rgba(6d1e05ff)",

    on_secondary_fixed = "rgba(ffbcaaff)",

    on_secondary_fixed_variant = "rgba(f68463ff)",

    tertiary_fixed = "rgba(2e2300ff)",

    tertiary_fixed_dim = "rgba(483800ff)",

    on_tertiary_fixed = "rgba(ecc95cff)",

    on_tertiary_fixed_variant = "rgba(c1a138ff)",

    foreground = "rgba(735d57ff)",

    surface_variant = "rgba(43312bff)",

}

return colors
