$image = /home/blx/.local/wallpapers/wallhaven-1ppgmv.jpg

$primary = rgba(97ab62ff)

$on_primary = rgba(121a00ff)

$primary_container = rgba(303f01ff)

$on_primary_container = rgba(98ac63ff)

$primary_fixed = rgba(1d2800ff)

$primary_fixed_dim = rgba(303f01ff)

$on_primary_fixed = rgba(c0d587ff)

$on_primary_fixed_variant = rgba(98ac63ff)

$secondary = rgba(9fa688ff)

$on_secondary = rgba(141a06ff)

$secondary_container = rgba(363d25ff)

$on_secondary_container = rgba(a0a789ff)

$secondary_fixed = rgba(212711ff)

$secondary_fixed_dim = rgba(363d25ff)

$on_secondary_fixed = rgba(c9cfafff)

$on_secondary_fixed_variant = rgba(a0a789ff)

$tertiary = rgba(7eaca3ff)

$on_tertiary = rgba(001c18ff)

$tertiary_container = rgba(11413bff)

$on_tertiary_container = rgba(7fada4ff)

$tertiary_fixed = rgba(002a25ff)

$tertiary_fixed_dim = rgba(11413bff)

$on_tertiary_fixed = rgba(a6d5ccff)

$on_tertiary_fixed_variant = rgba(7fada4ff)

$error = rgba(ff7b6eff)

$on_error = rgba(390001ff)

$error_container = rgba(7b0007ff)

$on_error_container = rgba(ff7d70ff)

$surface = rgba(12140dff)

$on_surface = rgba(cbcbc0ff)

$on_surface_variant = rgba(a2a495ff)

$surface_dim = rgba(12140dff)

$surface_bright = rgba(383a32ff)

$surface_container_lowest = rgba(0d0f08ff)

$surface_container_low = rgba(1b1c15ff)

$surface_container = rgba(1f2019ff)

$surface_container_high = rgba(292b23ff)

$surface_container_highest = rgba(34362dff)

$surface_variant = rgba(45483cff)

$outline = rgba(909284ff)

$outline_variant = rgba(393b30ff)

$shadow = rgba(000000ff)

$scrim = rgba(000000ff)

$inverse_surface = rgba(e3e3d7ff)

$inverse_on_surface = rgba(474940ff)

$inverse_primary = rgba(596b2aff)

$background = rgba(12140dff)

$on_background = rgba(62635aff)
