-- Generated by blxshell col_gen. Do not edit manually.
local colors = {
    image = [[{{ image }}]],
{% for name, value in colors.items() %}
    {{ name }} = "rgba({{ value.hex_stripped }}ff)",
{% endfor %}
}

return colors
