-- ZWM color module — auto-generated by col_gen, do not edit manually
-- Source: {{image}}
return {
    primary        = "{{colors.primary.default.hex}}",
    primaryDim     = "{{colors.primary_container.default.hex}}",
    outline        = "{{colors.outline.default.hex}}",
    outlineVariant = "{{colors.outline_variant.default.hex}}",
    tertiary       = "{{colors.tertiary.default.hex}}",
    error          = "{{colors.error.default.hex}}",
}
